// <auto-generated />
using System;
using EniHRWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EniHRWebAPI.Migrations.MyUsersDB
{
    [DbContext(typeof(MyUsersDBContext))]
    [Migration("20181206123622_migrations-ver2")]
    partial class migrationsver2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EniHRWebAPI.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActiveStatus");

                    b.Property<string>("Email");

                    b.Property<bool>("IsFirstLogon");

                    b.Property<DateTime?>("LastLogon");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Surname");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EniHRWebAPI.Models.UserAction", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActionDateTime");

                    b.Property<string>("ActionDescription");

                    b.Property<string>("ActionType");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("UserActions");
                });
#pragma warning restore 612, 618
        }
    }
}
